Profile/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "Profile"

urlpatterns = [

    path('<str:name>/', views.profile, name = "profile"),
    path('edit/<str:name>/', views.profileEdit, name = "profilEdit")


]

article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "article"

urlpatterns = [
    path('dashboard/', views.dashboard, name = "dashboard"),
    path('addarticle/', views.addArticle, name = "addarticle"),
    path('article/<int:id>', views.detail, name = "detail"),
    path('update/<int:id>', views.updateArticle, name = "update"),
    path('delete/<int:id>', views.deleteArticle, name = "delete"),
    path('', views.articles, name = "articles"),
    path('comment/<int:id>', views.addComment, name = "comment"),
    path('comment_delete/<int:id>', views.deleteComment, name = "comment_delete"),
    path('yazilim/', views.yazilim, name = "yazilim"),
    path('siir/', views.siir, name = "siir"),
    path('fikir/', views.fikir, name = "fikir"),
    path('teknoloji/', views.teknoloji, name = "teknoloji"),
    path('oyku/', views.oyku, name = "oyku"),
    path('bilim/', views.bilim, name = "bilim"),
    path('egitim/', views.egitim, name = "egitim"),
    path('ara/', views.ara, name="ara"),
    path('commentOfcomment/<int:id>', views.addCommentofComment, name="commentOfComment"),
    path('comment_re_delete/<int:id>', views.deleteCommentOfComment, name="comment_re_delete")
    
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = "index"),
    path('about/', views.about, name = "about"),
    path('articles/', include("article.urls")),
    path('user/', include("user.urls")),
    path('profile/', include("Profile.urls")),
    path('ads.txt/', views.ad)
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = "user"

urlpatterns = [

    path('register/', views.register, name = "register"),
    path('login/', views.loginUser, name = "login"),
    path('logout/', views.logoutUser, name = "logout"),
    path('change_password/', views.change_password, name = "change_pass")
    

]

Profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    user_picture = models.FileField(blank = True,null = True,verbose_name="Profil Fotoğrafı")
    bio = models.TextField(max_length=500, blank=True, verbose_name="Biyografi")
    birth_date = models.DateField(null=True, blank=True, verbose_name="Doğum Tarihi")
    
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Article(models.Model):
    
    YAZILIM = 'Yazılım'
    SIIR = 'Şiir'
    FIKIR = 'Fikir'
    TEKNOLOJI = 'Teknoloji'
    OYKU = 'Öykü'
    BILIM = 'Bilim'
    EGITIM = 'Eğitim'
    
    
    kategoriler = [
        (YAZILIM, 'Yazılım'),
        (SIIR, 'Şiir'),
        (FIKIR, 'Fikir'),
        (TEKNOLOJI, 'Teknoloji'),
        (OYKU, 'Öykü'),
        (BILIM, 'Bilim'),
        (EGITIM, 'Eğitim'),        
    ]
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name = "Yazar")
    title = models.CharField(max_length = 50,verbose_name = "Başlık")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")
    article_image = models.FileField(blank = True,null = True,verbose_name="Fotoğraf Ekle")
    kategori = models.TextField(choices=kategoriler,verbose_name="Kategori", default = 'Yok')
    viewNumber = models.IntegerField(verbose_name="Görüntülenme", default=0)
    onay = models.BooleanField(verbose_name="Onay", default=False)
    
    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']

class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE,verbose_name = "Makale",related_name="comments")
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name = "Yazar", null = True)
    comment_content = models.CharField(max_length = 200,verbose_name = "Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)
    comment_id = models.AutoField(primary_key=True)


    def __str__(self):
        return self.comment_content

    class Meta:
        ordering = ['-comment_date']

class CommentOfComment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE,verbose_name="Makale", null=True)
    comment = models.ForeignKey(Comment, on_delete = models.CASCADE, verbose_name="Yorumun yorumu", related_name="commentOfComment")
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name = "Yazar", null = True)
    commentOfComment_content = models.CharField(max_length = 100,verbose_name = "Yorum", null=True)
    commentOfComment_date = models.DateTimeField(auto_now_add=True)
    commentOfComment_id = models.AutoField(primary_key=True)


    def __str__(self):
        return self.commentOfComment_content or ''

    class Meta:
        ordering = ['-commentOfComment_date']



Profile/forms.py
from django import forms
from .models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["bio", "birth_date", "user_picture"]

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content", "article_image", "kategori"]

Profile/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .forms import ProfileForm
from .models import Profile, User
from django.contrib import messages
from article.models import Article

# Create your views here.

def profile(request, name):
    user = get_object_or_404(User, username=name)
    profile = Profile.objects.filter(user=user).first()
    articles = Article.objects.filter(author=user, onay=True)
    return render(request, "profile.html", {"user":user, "profile":profile, "articles":articles})

def profileEdit(request, name):
    user = get_object_or_404(User, username=name)
    profile = Profile.objects.filter(user=user).first()
    form = ProfileForm(request.POST or None, request.FILES or None, instance=profile)
    if user == request.user:
        if form.is_valid():
        
            profile = form.save(commit=False)
            profile.user = user
            profile.save()
            messages.success(request, "Profil başarıyla güncellendi.")

            return redirect("index")
    else:
        messages.info(request, "Başkasının makalesini güncellemeye yetkiniz yok.")
        return redirect("index")
    context = {
            "form" : form
    }

    return render(request, "profileEdit.html" ,context)

article/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, reverse
from .forms import ArticleForm
from django.contrib import messages
from .models import Article,Comment,CommentOfComment
from django.contrib.auth.decorators import login_required
import time


# Create your views here.


def index(request):
    articles = Article.objects.filter(onay=True).all()[:5]
    print(type(articles))
    return render(request, "index.html", {"articles":articles})

def ad(request):
    line = "google.com, pub-3937502118941434, DIRECT, f08c47fec0942fa0"
    return HttpResponse(line)

def about(request):
    return render(request, "about.html")
@login_required(login_url = "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles":articles
    }
    return render(request, "dashboard.html", context)
@login_required(login_url = "user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()

        messages.success(request, "Makale başarıyla eklendi.")
        return redirect("article:dashboard")

    return render(request, "addarticle.html", {"form" : form})

def detail(request, id):
    #article = Article.objects.filter(id = id).first()

    article = get_object_or_404(Article, id = id)
    comments = article.comments.all()
    comment_re = CommentOfComment.objects.filter(article=article)
    onay = article.onay

    time.sleep(2)
    article.viewNumber += 1
    article.save()
    return render(request, "detail.html", {"article": article, "comments":comments, "comments_re":comment_re, "onay":onay})
    
    

@login_required(login_url = "user:login")
def updateArticle(request, id):
    article = get_object_or_404(Article, id = id)
    form = ArticleForm(request.POST or None, request.FILES or None, instance=article)
    if article.author == request.user:
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.save()
            messages.success(request, "Makale başarıyla güncellendi.")
            return redirect("article:dashboard")
    else:
        messages.info(request, "Başkasının makalesini güncellemeye yetkiniz yok.")
        return redirect("article:dashboard")
        


    return render(request, "update.html", {"form":form})
@login_required(login_url = "user:login")
def deleteArticle(request, id):
    article = get_object_or_404(Article, id=id)
    if article.author == request.user:
        article.delete()
        messages.success(request, "Makale Başarıyla Silindi")
        return redirect("article:dashboard")
    else:
        messages.info(request, "Başkasının makalesini silmeye yetkiniz yok.")
        return redirect("article:dashboard")

def articles(request):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains = keyword).filter(onay=True)
        return render(request, "articles.html", {"articles":articles})

    articles = Article.objects.all().filter(onay=True)

    return render(request, "articles.html", {"articles":articles})

@login_required(login_url = "user:login")
def addComment(request, id):
    article = get_object_or_404(Article, id=id)
    if request.method == "POST":
        
        comment_content = request.POST.get("comment_content")
        dogrulamaComment = Comment.objects.filter(author = request.user, article = article, comment_content = comment_content)

        if dogrulamaComment:
            messages.info(request, "Tekrarlanan yorum tespit edildi")
            return redirect(reverse("article:detail", kwargs={"id":id}))
        else:
            newComment = Comment(comment_content=comment_content)
            newComment.author = request.user
            newComment.article = article
            newComment.save()
    return redirect(reverse("article:detail", kwargs={"id":id}))


@login_required(login_url = "user:login")
def deleteComment(request, id):
    comment = get_object_or_404(Comment, comment_id = id)
    if comment.author == request.user:
        comment.delete()
    else:
        messages.info(request, "Bro...")
    article = comment.article
    return redirect(reverse("article:detail", kwargs={"id":article.id}))

def yazilim(request):
    articles = Article.objects.filter(kategori = 'Yazılım').filter(onay=True)
    if articles:
        return render(request, "articles.html", {"articles":articles})
    messages.info(request, "Maalesef bu kategoride bir yazı bulunmuyor.")
    articles = Article.objects.all()
    return render(request, "articles.html", {"articles":articles})
    
    

def siir(request):
    articles = Article.objects.filter(kategori = 'Şiir').filter(onay=True)
    if articles:
        return render(request, "articles.html", {"articles":articles})
    
    messages.info(request, "Maalesef bu kategoride bir yazı bulunmuyor.")
    articles = Article.objects.all()
    return render(request, "articles.html", {"articles":articles})

def fikir(request):
    articles = Article.objects.filter(kategori = 'Fikir').filter(onay=True)
    if articles:
        return render(request, "articles.html", {"articles":articles})
    messages.info(request, "Maalesef bu kategoride bir yazı bulunmuyor.")    
    articles = Article.objects.all()
    return render(request, "articles.html", {"articles":articles})

def teknoloji(request):
    articles = Article.objects.filter(kategori = 'Teknoloji').filter(onay=True)
    if articles:
        return render(request, "articles.html", {"articles":articles})
    
    messages.info(request, "Maalesef bu kategoride bir yazı bulunmuyor.")
    articles = Article.objects.all()
    return render(request, "articles.html", {"articles":articles})

def oyku(request):
    articles = Article.objects.filter(kategori = 'Öykü').filter(onay=True)
    if articles:
        return render(request, "articles.html", {"articles":articles})
    
    messages.info(request, "Maalesef bu kategoride bir yazı bulunmuyor.")
    articles = Article.objects.all()
    return render(request, "articles.html", {"articles":articles})

def bilim(request):
    articles = Article.objects.filter(kategori = 'Bilim').filter(onay=True)
    if articles:
        return render(request, "articles.html", {"articles":articles})
    
    messages.info(request, "Maalesef bu kategoride bir yazı bulunmuyor.")
    articles = Article.objects.all()
    return render(request, "articles.html", {"articles":articles})

def egitim(request):
    articles = Article.objects.filter(kategori = 'Eğitim').filter(onay=True)
    if articles:
        return render(request, "articles.html", {"articles":articles})
    
    messages.info(request, "Maalesef bu kategoride bir yazı bulunmuyor.")
    articles = Article.objects.all()
    return render(request, "articles.html", {"articles":articles})




def ara(request):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains = keyword).filter(onay=True)
        return render(request, "articles.html", {"articles":articles})

    articles = Article.objects.all()

    return render(request, "articles.html", {"articles":articles})

@login_required(login_url = "user:login")
def addCommentofComment(request, id):
    comment = get_object_or_404(Comment, comment_id=id)
    article = comment.article
    if request.method == "POST":

        comment_content = request.POST.get("comment_re_content")
        dogrulamaComment = CommentOfComment.objects.filter(author = request.user, comment = comment, commentOfComment_content = comment_content)
        
        if dogrulamaComment:
            messages.info(request, "Tekrarlanan cevap tespit edildi")
            return redirect(reverse("article:detail", kwargs={"id":comment.article.id}))
        else:
            newCommentRe = CommentOfComment(commentOfComment_content=comment_content)
            newCommentRe.author = request.user
            newCommentRe.comment = comment
            newCommentRe.article = article
            newCommentRe.save()
    return redirect(reverse("article:detail", kwargs={"id":comment.article.id}))


login_required(login_url="user:login")
def deleteCommentOfComment(request, id):
    comment_re = get_object_or_404(CommentOfComment, commentOfComment_id=id)
    if comment_re.author == request.user:
        comment_re.delete()
        messages.success(request, "Yorum Başarıyla Silindi")
        return redirect(reverse("article:detail", kwargs={"id":comment_re.comment.article.id}))
    else:
        messages.info(request, "Başkasının yorumunu silmeye yetkiniz yok.")
        return redirect(reverse("article:detail", kwargs={"id":comment_re.comment.article.id}))



    



    

templates/about.html
{% extends "layout.html" %}
{% block body %}
<br>

<h3>Hakkımızda</h3>
<hr>
{% load static %}

<p style="font-size: 20px">
    Biz, gençlerden oluşan bir ekip olarak bu işe adım atarken inandık...<br>
    Üzerine düşünülmüş, yorum yapılmış dolayısıyla işlenmiş bilginin çağımızın cevheri olduğunu biliyorduk ve bu değerlerin diğer insanlarla da paylaşılması gerektiğine inandık. 
    Geleceğin gençlerin olduğunu, onu bizim şekillendireceğimizi gördük, kendimize inandık. 
    Belki, bir şekilde bu site ile insanlığa, gençliğe ve bilginin kendisine hizmet edebileceğimize inandık. 
    mustakil.cc ‘de güncel her alanda yazılar paylaşılıyor. 
    Kullanıcılar, sosyal bilimlerden savunma sanayiine, tercümelerden teknolojiye birçok konuda makalelere tek tık ile erişim sağlayabiliyor. 
    Ayrıca, yetkin olduğu alanda kendi makalelerini de paylaşıp hem diğer kullanıcıları aydınlatıyor hem de onların yapıcı eleştirileri ile kendini geliştiriyor. 
    Bu anlamda bir bilgi havuzu oluşturuyoruz. 
    Biz, burada sadece araç konumundayız ve temel amacımız, 
    özgün ve kaliteli bilgiye en kolay biçimde ulaşımının sağlanmasına ve emek harcanarak oluşturulan yazıların kolayca paylaşılmasına yardım edebilmek. 
    <br><br>Siz de bizim inandıklarımıza inanıyorsanız, kolayca kaydolup toplumun geleceğine ve bilgiye hizmet etmeye başlayabilirsiniz.
</p>

{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}



<div class="row">
        <div class="col-md-6 offset-md-3">
        <h3>Makale Ekle</h3>
        <hr>
        <form method="POST" enctype="multipart/form-data">
                {{form.media}}
                {% csrf_token %}
                {{form|crispy}}
                <br>
                <button type="submit" class="btn btn-danger">Ekle</button>
            </form>

        </div>
      </div>

{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}
{% load static %}
<br>
<div class="row">
  <div class="col-3" style="margin-top: 12px; margin-right: 45px">
  <h3><strong>Yazılar</strong></h3>

  </div>
  <div class="col-5">

      <nav class="navbar navbar-expand-lg navbar-light rounded">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample10" aria-controls="navbarsExample10" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      
          <div class="collapse navbar-collapse justify-content-end" id="navbarsExample10">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link border-right" href="{% url 'article:teknoloji' %}">Teknoloji</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link border-right" href="{% url 'article:oyku' %}">Öykü</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link border-right" href="{% url 'article:bilim' %}">Bilim</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link border-right" href="{% url 'article:egitim' %}">Eğitim</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link border-right" href="{% url 'article:yazilim' %}">Yazılım</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link border-right" href="{% url 'article:siir' %}">Şiir</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'article:fikir' %}">Fikir</a>
              </li>
              
            </ul>
          </div>
        </nav>

        <!--<nav class="site-header sticky-top py-1">
      <div class="container d-flex flex-column flex-md-row justify-content-between">
        <a class="py-2" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="d-block mx-auto"><circle cx="12" cy="12" r="10"></circle><line x1="14.31" y1="8" x2="20.05" y2="17.94"></line><line x1="9.69" y1="8" x2="21.17" y2="8"></line><line x1="7.38" y1="12" x2="13.12" y2="2.06"></line><line x1="9.69" y1="16" x2="3.95" y2="6.06"></line><line x1="14.31" y1="16" x2="2.83" y2="16"></line><line x1="16.62" y1="12" x2="10.88" y2="21.94"></line></svg>
        </a>
        <a class="py-2 d-none d-md-inline-block" href="#">Tour</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Product</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Features</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Enterprise</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Support</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Pricing</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Cart</a>
      </div>
    </nav>
    -->


  </div>
</div>
<hr>
<br>
  <!--
      <form class="form-inline md-form mr-auto mb-4 input-group">
          {% csrf_token %}
          <input type="text" name="keyword" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button type="submit" class="btn btn-primary" type="danger">Ara</button>
        </form>-->
</ul>



  <br><br>


{% if articles %}

<!--
<table class="table table-striped table-hover table-responsive-sm">
        <thead>
          <tr>
            <th scope="col">Başlık</th>
            <th scope="col">Yazar</th>
            <th scope="col">Tarih</th>
            <th scope="col">Kategori</th>
          </tr>
        </thead>
        <tbody>-->
          <div class="card-columns">

              <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
              <!-- Küçük Yatay -->
              <ins class="adsbygoogle"
                   style="display:inline-block;width:300px;height:100px; align-content: center"
                   data-ad-client="ca-pub-3937502118941434"
                   data-ad-slot="4526537755"></ins>
              <script>
                   (adsbygoogle = window.adsbygoogle || []).push({});
              </script>
              
{% for article in articles %}

<div class="card" style="width: 18rem; margin-top: 15px">

{% if article.article_image %}
  <img src="{{article.article_image.url}}" class="card-img-top" alt="">
        {% endif %}
  <div class="card-body">
    <h5 class="card-title"><strong>{{article.title|safe|striptags}}</strong></h5>
    <p class="card-text">{{article.content|safe|truncatewords:40|striptags}}</p>
    <hr>
    <a href="{% url 'article:detail' article.id %}" class="btn btn-primary">Devamını Oku</a>
    <div class="row" style="margin-top: 7%;">
      <div class="col-1" style="margin-top: 1%">
        <img src="{% static 'img/userIcon.png' %}" alt="" width="15" height="15">
      </div>
      <div class="col-4" style="margin-top: 1.1%">
        <p><a href="{% url 'Profile:profile' article.author %}">{{article.author}}</a></p>
      </div>
      <div class="col-2">
        <img src="{% static 'img/viewIcon.png' %}" alt="" width="40" height="30">
      </div>
      <div class="col-3" style="margin-top: 1.1%">
        <p>{{article.viewNumber}}</p>
      </div>
      
    </div>
  </div>
</div>
<!--
<tr>
            <td><a href="{% url 'article:detail' article.id %}"><strong>{{article.title}}</strong></a></td>
            <td>{{article.author.username}}</td>
            <td>{{article.created_date}}</td>
            <td>{{article.kategori}}</td>
            
          </tr>      
            -->
{% endfor %}


<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Dikey -->
<ins class="adsbygoogle"
     style="display:inline-block;width:270px;height:500px"
     data-ad-client="ca-pub-3937502118941434"
     data-ad-slot="3731512596"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>


</div>

{% else %}
<div class="alert alert-danger">
    Makale Bulunamadı
</div>
{% endif %}

{% endblock body %}

templates/change_password.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}


<div class="row">
        <div class="col-md-6 offset-md-3">
        <h3>Şifreyi Değiştir</h3>
        <hr>
        <form method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <br>
                <button type="submit" class="btn btn-danger">Değiştir</button>
                
            </form>

        </div>
      </div>



{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<h3>Kontrol Paneli</h3>
<hr>
<p>
    Hoşgeldiniz, <small>{{request.user.username}}</small>
</p>
<hr>
<a class="btn btn-danger" href="/articles/addarticle">Yazı Ekle</a>
<hr>

{% if articles %}
<div class="row">
    <div class="col">
<table class="table table-striped table-hover table-responsive-sm" style="background-color: #DFF6FF">
        <thead class="table-dark" style="background-color: #0087A8">
          <tr>
            <th scope="col">id</th>
            <th scope="col">Başlık</th>
            <th scope="col">Yazar</th>
            <th scope="col">Tarih</th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
            {% for article in articles %}
            <tr>
            <th scope="row">{{article.id}}</th>
            <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
            <td>{{article.author.username}}</td>
            <td>{{article.created_date}}</td>
            <td><a class="btn btn-warning" href="{% url 'article:update' article.id %}">Güncelle</a></td>
            <td><a class="btn btn-danger" href="{% url 'article:delete' article.id %}">Sil</a></td>
          </tr>          
            {% endfor %}
          <!----->
          
        </tbody>
      </table>
      </div>
      </div>

{% else %}
<div class="alert alert-danger">Henüz bir yazınız bulunmuyor :(</div>
{% endif %}



{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}">
    <title>Müstakil</title>
    <script data-ad-client="ca-pub-3937502118941434" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
</head>
<body>
    {% include "includes/navbar.html" %}

<!--<img src="{% static 'img/banner.png' %}" class="img-fluid" alt="" style="width: 100%">-->


    
            
    
    <div class="container" style = "margin-bottom:10px;">
    {% if messages %}
            {% for message in messages %}
            {% if message.tags == "info" %}
            <br><br>
            <div class="alert alert-danger">{{ message }}</div>
            {% else %}
            <br><br>
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endif %}
            {% endfor %}

        {% endif %}

    <br>
    {% block body %}

    
    {% endblock body %}

    </div>

    {% block index %}
    
    {% endblock index %}

<style>
  html, body {
    height: 80%;
  }
  
  #wrap {
    min-height: 100%;
  }
  
  #main {
    overflow:auto;
    padding-bottom:100px; /* this needs to be bigger than footer height*/
  }

  .footer {
    position: relative;
    margin-top: -60px; /* negative value of footer height */
    height: 60px;
    clear:both;
    padding-top:20px;
  } 
</style>
<div id="wrap">
  
</div>
<footer id="footer" class="footer text-white" style="background-color: #380058;
">
  <div class="text-center">
    <small>Copyright &copy; mustakil.cc</small>
  </div>
</footer>
    
    
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>

</body>
</html>

templates/profileEdit.html
{% extends 'layout.html' %}

{% block body %}
{% load crispy_forms_tags %}

        <h3>{{user}} profili</h3>
        <hr>

        <form method="POST" enctype="multipart/form-data">
                {{form.media}}
                {% csrf_token %}
                {{form|crispy}}
                
        <a class="btn btn-warning" href="{% url 'user:change_pass' %}">Şifreni Değiştir</a><br><br><br><br>
                <button type="submit" class="btn btn-primary">Kaydet</button>
            </form>


{% endblock body %}